### ISSUE TITLE
Raspberry Pi 3B+ Bookworm 64 bit & Tempcomp

### ISSUE THREAD

**Issue by phipac** [tiagofreire-pt/rpi_adafruit_stratum1_chrony#1]
Greetings, all! Great tutorial. I have a stable setup now with my 3B+ on the new Bookworm 64 bit OS. The only thing from this tutorial that doesn't work is the tempcomp section. In my chrony.conf file, I have the command listed exactly as it is in this tutorial:

`tempcomp /sys/class/thermal/thermal_zone0/temp 30 /etc/chrony/chrony.tempcomp`

My /etc/chrony/chrony.tempcomp file is populated exactly as shown in the tutorial:

20000 0
21000 0
25000 0
30000 0
40000 0

When restarting the chrony service, I get the following error:

Fatal error : Could not read tempcomp point from /etc/chrony/chrony.tempcomp

Did something change with the new OS, or am I missing a step somewhere? Thank you for your help!

**Comment by tiagofreire-pt** [comment]
Hi, @phipac .

Could you share the result of this command?

```ls -la /etc/chrony/chrony.tempcomp```

Thanks.

**Comment by phipac** [comment]
> Hi, @phipac .
> 
> Could you share the result of this command?
> 
> `ls -la /etc/chrony/chrony.tempcomp`
> 
> Thanks.

Of course - thank you for your time.

-rw-r--r-- 1 root root 41 Oct 22 16:54 /etc/chrony/chrony.tempcomp

**Comment by phipac** [comment]
Nevermind. I had a blank line at the end of the file. It's fine now.
