### ISSUE TITLE
Syntax typo

### ISSUE THREAD

**Issue by jurisuk** [tiagofreire-pt/rpi_adafruit_stratum1_chrony#3]
This has caused me some hair-pulling. In the setup of GPSD daemon section, there is an unmatched quotation mark:
```
DEVICES="/dev/ttyAMA0 /dev/pps0″
```
The line should read:
```
DEVICES="/dev/ttyAMA0 /dev/pps0"
```
Thanks for the tutorial!

**Comment by tiagofreire-pt** [comment]
Hi, @jurisuk .

Thanks for noticing it. I harmonized that.

Best regards.
