### ISSUE TITLE
Typo: Setup the GPSd daemon

### ISSUE THREAD

**Issue by phipac** [tiagofreire-pt/rpi_adafruit_stratum1_chrony#4]
Great tutorial! There is a typo in the Setup the GPSd daemon section of code. One line contains the weird quotation mark instead of the "standard" mark. Honest it had me on a chase for two days.

`START_DAEMON="true"
USBAUTO="false"
DEVICES="/dev/ttyAMA0 /dev/pps0″
GPSD_OPTIONS="--nowait --passive --speed 9600"`

Notice DEVICES has the quirky quote at the end.

**Comment by tiagofreire-pt** [comment]
@phipac , thanks for noticing that!
