### ISSUE TITLE
chrony tempcomp

### ISSUE THREAD

**Issue by phipac** [tiagofreire-pt/rpi_adafruit_stratum1_chrony#5]
I can't seem to get that to work. I get the following error when trying to enable tempcomp:

chronyd[79733]: Fatal error : Could not read tempcomp point from /etc/chrony/chrony.tempcomp

I tried playing with the permissions but no luck. System information below:

PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
Model           : Raspberry Pi 3 Model B Plus Rev 1.3
Linux gps-pi 6.6.31+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux

Thanks for your great work!

**Comment by tiagofreire-pt** [comment]
@phipac , paste here the result of the command:

```
ls -la /etc/chrony/chrony.tempcomp 
```

It should be similar to:

```
-rw-r--r-- 1 root root 88 Jan  5 20:30 /etc/chrony/chrony.tempcomp
```

**Comment by phipac** [comment]
@tiagofreire-pt 

 $ ls -la /etc/chrony/chrony.tempcomp
-rwxrwxrwx 1 root root 89 Jun 12 16:14 /etc/chrony/chrony.tempcomp

**Comment by tiagofreire-pt** [comment]
Make sure the content of that file is verbatim to the proposed one:

https://github.com/tiagofreire-pt/rpi_adafruit_stratum1_chrony?tab=readme-ov-file#create-a-simple-and-innocuous-temperature-calibration-file-for-chrony

**Comment by phipac** [comment]
For whatever reason, it is working now. I may have inadvertently fixed a typo somewhere, or some nice gremlin intervened. Whatever the case, tempcomp is now working.

Speaking of typos, I fixed two minor ones on lines 379 and 381.

Thanks for your work and help!
